{
  imports = [
    ./wakatime.nix
    ./auto-pairs.nix
    ./colorizer.nix
    ./autosave.nix
    ./autotag.nix
    ./blankline.nix
    ./commentary.nix
    ./dashboard.nix
    ./gitsigns.nix
    ./lazygit.nix
    ./markdown-preview.nix
    ./todo-comments.nix
    ./toggleterm.nix
    ./which-key.nix
    ./wilder.nix
    ./undotree.nix
    ./lua-snip.nix
  ];
}
